name: Ejecucion Bots Financieros

on:
  schedule:
    # Lunes a Viernes a las 16:45 de Argentina (19:45 UTC)
    - cron: '45 19 * * 1-5'
  workflow_dispatch: # Esto activa un botón para correrlo a mano

jobs:
  analisis-mercado:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar herramientas
        run: pip install yfinance pandas scikit-learn matplotlib requests lxml

      - name: Ejecutar Bot Swing (Corto Plazo)
        run: python bot_tactico_5dias.py

      - name: Ejecutar Bot Macro (Largo Plazo)
        run: python bot_estructural_1mes.py
      - name: Ejecutar Radar Commodities
        run: python bot_commodities.py
